name: online_bazar
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  flutter_svg: ^2.0.10+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
  firebase_auth: ^5.3.1
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  http: ^1.2.2
  shimmer: ^3.0.0
  mask_text_input_formatter: ^2.9.0
  img_picker: ^1.0.2
  firebase_storage: ^12.3.2
  yandex_mapkit: ^4.1.0
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/icons/
    - assets/icons/
    - assets/images/