// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj9A40I4MucpPDcJGJAg0fY95XDOJYdCk',
    appId: '1:169703264569:android:86782eceefdffcf9e218e8',
    messagingSenderId: '169703264569',
    projectId: 'online-shop-c61f7',
    databaseURL: 'https://online-shop-c61f7-default-rtdb.firebaseio.com',
    storageBucket: 'online-shop-c61f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ_UhtZp4bWSNT7MwHtl3Rc-eoct51WC4',
    appId: '1:169703264569:ios:d2fa7fcfa2759a7ee218e8',
    messagingSenderId: '169703264569',
    projectId: 'online-shop-c61f7',
    databaseURL: 'https://online-shop-c61f7-default-rtdb.firebaseio.com',
    storageBucket: 'online-shop-c61f7.appspot.com',
    iosBundleId: 'com.bazar.uz.bazar',
  );

}